[output]
tileset_width = 21717

[providers."minecraft:font/ascii.png"]
width = 8
height = 8

[providers."minecraft:font/nonlatin_european.png"]
width = 8
height = 8

[providers."minecraft:font/accented.png"]
width = 9
height = 12