["minecraft:font/ascii.png"]
width = 8
height = 8
gap_x = 0
gap_y = 0

["minecraft:font/nonlatin_european.png"]
width = 8
height = 8
gap_x = 0
gap_y = 0

["minecraft:font/accented.png"]
width = 9
height = 12
gap_x = 0
gap_y = 0