name: CI
on: push
jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.3/install.sh | sh
      - name: Set up Ruff
        run: uv tool install ruff
      - name: Run Ruff linter
        run: ruff check --output-format=github
      - name: Run Ruff format
        run: ruff format --check
